# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 47, 770, 541))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton_add_info = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_info.setGeometry(QtCore.QRect(10, 10, 380, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton_add_info.setFont(font)
        self.pushButton_add_info.setObjectName("pushButton_add_info")
        self.pushButton_chang_info = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_chang_info.setGeometry(QtCore.QRect(400, 10, 380, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton_chang_info.setFont(font)
        self.pushButton_chang_info.setObjectName("pushButton_chang_info")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Информация о кофе"))
        self.pushButton_add_info.setText(_translate("MainWindow", "Добавить информацию о кофе"))
        self.pushButton_chang_info.setText(_translate("MainWindow", "Редактировать информацию о кофе"))
